const baseWS = {
  arms_property: {
    critPercent: '1',
    critBoostNum: '9',
    finalDamageBoostPercent: '',
    physicalDamagePercent: '2.4',
    physicalDamage: '7277',
  },
  head_property: {
    physicalReductionPercent: '',
    spellReductionPercent: '',
    physicalDefense: '3000',
    spellDefense: '2700',
    hpPercent: '2.5',
    hp: '30000',
  },
  cloth_property: {
    physicalReductionPercent: '',
    spellReductionPercent: '',
    hpPercent: '2.5',
    hp: '30000',
    physicalDefense: '2940',
    spellDefense: '2500',
  },
  pants_property: {
    physicalReductionPercent: '',
    spellReductionPercent: '',
    hpPercent: '2.5',
    spellDefense: '2000',
    hp: '30000',
    physicalDefense: '3000',
  },
  shoes_property: {
    physicalReductionPercent: '',
    spellReductionPercent: '',
    hpPercent: '2.5',
    hp: '30000',
    spellDefense: '2600',
    physicalDefense: '2887',
  },
  necklace_property: {
    hp: '13000',
    physicalDamage: '2300',
    finalDamageBoostPercent: '',
    hpPercent: '',
    physicalDamagePercent: '',
    critPercent: '0.3',
    physicalDefense: '1100',
  },
  pendant_property: {
    hp: '13000',
    physicalDamage: '2227',
    physicalDefense: '1100',
    critBoostNum: '',
    critPercent: '0.3',
  },
  ring1_property: {
    hp: '13000',
    physicalDamage: '2100',
    physicalDamagePercent: '',
    physicalDefense: '',
    finalDamageBoostPercent: '',
    critPercent: '0.3',
    spellDefense: '1100',
  },
  ring2_property: {
    hp: '13000',
    physicalDamage: '2366',
    critPercent: '0.3',
    critBoostNum: '',
    physicalReductionPercent: '',
    spellDefense: '1100',
  },
  name: '小兵一号',
  level: '70',
  character: '武士',
  gang: '',
  country: '',
  arms: '珠联璧合·紫龙寂地·枪',
  arms_num: '12',
  head: '绝世教主·破阵·战盔',
  head_num: '12',
  cloth: '绝世教主·破阵·战甲',
  cloth_num: '12',
  pants: '绝世教主·破阵·下裳',
  shoes: '绝世教主·破阵·战靴',
  pants_num: '12',
  shoes_num: '12',
  necklace: '绝世教主·破阵·链',
  pendant: '绝世教主·破阵·坠',
  ring1: '绝世教主·破阵·戒',
  ring2: '绝世教主·破阵·戒',
  necklace_num: '12',
  pendant_num: '12',
  ring1_num: '12',
  ring2_num: '12',
  totoalProperty: {
    hp: 411320,
    physicalDamage: 39447,
    spellDamage: '0',
    physicalDefense: 28388,
    spellDefense: 24720,
    critPercent: 16,
    critBoostNum: 166,
    physicalReductionPercent: '0',
    spellReductionPercent: '0',
    physicalReboundPercent: '0',
    spellReboundPercent: '0',
    finalDamageBoostPercent: '5',
  },
  combatPower: 32704,
};

const tianwuyan = {
  arms_property: {
    critPercent: '2',
    critBoostNum: '10',
    finalDamageBoostPercent: '3',
    physicalDamagePercent: '3.2',
    physicalDamage: '9776',
  },
  head_property: {
    physicalReductionPercent: '1',
    spellReductionPercent: '1',
    physicalDefense: '3500',
    spellDefense: '3000',
    hpPercent: '3',
  },
  cloth_property: {
    physicalReductionPercent: '1.2',
    spellReductionPercent: '1.1',
    hpPercent: '2',
    hp: '37500',
    physicalDefense: '3000',
  },
  pants_property: {
    physicalReductionPercent: '1.3',
    spellReductionPercent: '0.8',
    hpPercent: '3',
    spellDefense: '3300',
    hp: '42000',
  },
  shoes_property: {
    physicalReductionPercent: '1',
    spellReductionPercent: '1',
    hpPercent: '2',
    hp: '27890',
    spellDefense: '2600',
  },
  necklace_property: {
    hp: '15000',
    physicalDamage: '3500',
    finalDamageBoostPercent: '0.6',
    hpPercent: '2',
    physicalDamagePercent: '1',
  },
  pendant_property: {
    hp: '14972',
    physicalDamage: '2800',
    physicalDefense: '1600',
    critBoostNum: '6',
    critPercent: '0.5',
  },
  ring1_property: {
    hp: '13984',
    physicalDamage: '2987',
    physicalDamagePercent: '1',
    physicalDefense: '1400',
    finalDamageBoostPercent: '0.5',
  },
  ring2_property: {
    hp: '19888',
    physicalDamage: '3077',
    critPercent: '0.8',
    critBoostNum: '7',
    physicalReductionPercent: '0.5',
  },
  name: '天无言',
  level: '70',
  character: '墨者',
  gang: '-名剑山庄-',
  country: '齐',
  arms: '笑苍生·岩鳞·枪',
  arms_num: '17',
  head: '笑苍生·岩鳞·战盔',
  head_num: '15',
  cloth: '笑苍生·岩鳞·战甲',
  cloth_num: '15',
  pants: '笑苍生·岩鳞·裳',
  shoes: '笑苍生·岩鳞·战靴',
  pants_num: '15',
  shoes_num: '15',
  necklace: '笑苍生·岩鳞·链',
  pendant: '笑苍生·岩鳞·坠',
  ring1: '笑苍生·岩鳞·戒',
  ring2: '笑苍生·岩鳞·戒',
  necklace_num: '17',
  pendant_num: '18',
  ring1_num: '19',
  ring2_num: '20',
};

const zoubeiye = {
  name: '邹北业',
  level: '70',
  character: '武士',
  gang: '黄埔军校',
  country: '楚',
  arms: '天怒·旷野孤疆·枪',
  arms_num: '19',
  arms_property: {
    physicalDamage: '10975',
    physicalDamagePercent: '3.6',
    critPercent: '2.7',
    critBoostNum: '15',
    finalDamageBoostPercent: '2.86',
  },
  head_property: {
    hp: '42055',
    physicalReductionPercent: '2',
    spellReductionPercent: '2',
    physicalDefense: '5500',
    spellDefense: '5377',
  },
  cloth_property: {
    hp: '42755',
    physicalReductionPercent: '1.5',
    spellReductionPercent: '2',
    physicalDefense: '5470',
    spellDefense: '5379',
  },
  pants_property: {
    hp: '',
    physicalDamage: '9996',
    critPercent: '3',
    critBoostNum: '16.2',
  },
  shoes_property: {
    hp: '40187',
    physicalReductionPercent: '2',
    spellReductionPercent: '1.7',
    physicalDefense: '5560',
    spellDefense: '5688',
  },
  necklace_property: {
    hp: '25798',
    hpPercent: '2.4',
    physicalReductionPercent: '1.1',
    spellReductionPercent: '1.2',
    finalDamageBoostPercent: '1.8',
  },
  pendant_property: {
    hp: '27631',
    hpPercent: '2.95',
    physicalReductionPercent: '1.2',
    spellReductionPercent: '0.96',
    finalDamageBoostPercent: '1.5',
  },
  ring1_property: {
    hp: '',
    hpPercent: '',
    physicalDamage: '14765',
    finalDamageBoostPercent: '',
  },
  ring2_property: {
    hp: '',
    physicalDamage: '14596',
    finalDamageBoostPercent: '',
  },
  head: '金晨曦·泣血·战盔',
  cloth: '金晨曦·泣血·战甲',
  pants: '塞鸿秋',
  shoes: '金晨曦·泣血·战靴',
  head_num: '17',
  cloth_num: '17',
  pants_num: '20',
  shoes_num: '17',
  necklace: '金晨曦·泣血·链',
  pendant: '金晨曦·泣血·坠',
  necklace_num: '17',
  pendant_num: '18',
  ring1: '泪泉',
  ring2: '泪泉',
  ring1_num: '20',
  ring2_num: '20',
  totoalProperty: {
    hp: 620796,
    physicalDamage: 219999,
    spellDamage: '0',
    physicalDefense: 50275,
    spellDefense: 50028,
    critPercent: 36,
    critBoostNum: 273,
    physicalReductionPercent: 20,
    spellReductionPercent: 20,
    physicalReboundPercent: '0',
    spellReboundPercent: '0',
    finalDamageBoostPercent: 24,
  },
  combatPower: 121485,
};

export const db = [baseWS, tianwuyan, zoubeiye];
